name: Action Part2

on: push
jobs:
  builds:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - name: Action Part2 Demo
          run: echo "This build successfully executed"
